version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - comparecai-network
      - planningpokergo-network

networks:
  comparecai-network:
    external: true
  planningpokergo-network:
    external: true
