services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
      - planningpokergo-network
  
  doclinic-frontend:
    image: cristianoaguiarofc/doclinic-frontend
    networks:
      - app-network
  
  doclinic-client-frontend:
    image: cristianoaguiarofc/doclinic-client-frontend
    networks:
      - app-network

  doclinic-backend:
    image: cristianoaguiarofc/doclinic
    environment:
      - MONGO_URI_AUTHENTICATOR=${MONGO_URI_AUTHENTICATOR}
      - MONGO_URI_CLIENT_AUTHENTICATOR=${MONGO_URI_CLIENT_AUTHENTICATOR}
      - MONGO_URI_CLIENT=${MONGO_URI_CLIENT}
      - MONGO_URI_ESTABLISHMENT=${MONGO_URI_ESTABLISHMENT}
      - MONGO_URI_SCHEDULING=${MONGO_URI_SCHEDULING}
    networks:
      - app-network

  planningpokergo-backend:
    image: cristianoaguiarofc/planningpokergo-backend
    networks:
      - planningpokergo-network

networks:
  app-network:
    driver: bridge
  planningpokergo-network:
    driver: bridge
