version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comparecai-network # Se o comparecai-backend precisar se conectar direto

networks:
  comparecai-network:
    external: true

volumes:
  postgres_data:
