name: Deploy Postgres

on:
  workflow_dispatch:

jobs:
  deploy-postgres:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            rm -rf vps-settings-cd
            git clone https://github.com/vps-settings/vps-settings-cd.git
            cd vps-settings-cd

            cat << 'EOF' > .env.postgres
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            EOF

            docker compose -f docker-compose.postgres.yml down
            
            # Garante que as redes externas existem na VPS antes do deploy
            docker network create comparecai-network || true
            docker network create planningpokergo-network || true
            
            docker compose -f docker-compose.postgres.yml up -d
